version: "3.1"
services:
    db:
        image: mysql
        ports:
            - "3307:3306"
        # command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: db_test
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    www:
        build: .
        ports:
            - "81:80"
        volumes:
            - ./www/html:/var/www/html
        depends_on:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8000:80
        environment:
            MYSQL_HOST: db
            MYSQL_USER: root
            MYSQL_PASSWORD: test123
            MYSQL_ROOT_PASSWORD: test123
        networks:
            - default
networks:
    default:
volumes:
    persistent:
